// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaOhbRhkpuuGPs7IUUAvZex0Sjuc1ZVa0',
    appId: '1:753672334475:web:1c19217088a8ab0cafb88e',
    messagingSenderId: '753672334475',
    projectId: 'entreprisejobs-app',
    authDomain: 'entreprisejobs-app.firebaseapp.com',
    storageBucket: 'entreprisejobs-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMB-Kn2_Jb86fy04Vpk36Jmv_0v_JUpck',
    appId: '1:753672334475:android:fc70576639395201afb88e',
    messagingSenderId: '753672334475',
    projectId: 'entreprisejobs-app',
    storageBucket: 'entreprisejobs-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTASvMZL6eHdPzhcfJqLdZE2o7psJaNZ0',
    appId: '1:753672334475:ios:bfb67db9845f3e34afb88e',
    messagingSenderId: '753672334475',
    projectId: 'entreprisejobs-app',
    storageBucket: 'entreprisejobs-app.firebasestorage.app',
    iosBundleId: 'com.example.entreprisejobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTASvMZL6eHdPzhcfJqLdZE2o7psJaNZ0',
    appId: '1:753672334475:ios:bfb67db9845f3e34afb88e',
    messagingSenderId: '753672334475',
    projectId: 'entreprisejobs-app',
    storageBucket: 'entreprisejobs-app.firebasestorage.app',
    iosBundleId: 'com.example.entreprisejobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaOhbRhkpuuGPs7IUUAvZex0Sjuc1ZVa0',
    appId: '1:753672334475:web:a60ccc592a515e35afb88e',
    messagingSenderId: '753672334475',
    projectId: 'entreprisejobs-app',
    authDomain: 'entreprisejobs-app.firebaseapp.com',
    storageBucket: 'entreprisejobs-app.firebasestorage.app',
  );
}
